# Generated by Django 3.1.6 on 2021-02-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('medium', models.CharField(max_length=50)),
                ('substrate', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='artwork/')),
            ],
            options={
                'verbose_name_plural': 'Artwork',
            },
        ),
    ]
